In [1]:
import pandas as pd

In [4]:
 df = pd.read_csv(r"/Users/jiyadariyani/Documents/Projects/Python Projects/Pandas Practice/Flavors.csv")

df.head()

In [5]:
df

,Flavor,Base Flavor,Liked,Flavor Rating,Texture Rating,Total Rating
0,Mint Chocolate Chip,Vanilla,Yes,10.0,8.0,18.0
1,Chocolate,Chocolate,Yes,8.8,7.6,16.6
2,Vanilla,Vanilla,No,4.7,5.0,9.7
3,Cookie Dough,Vanilla,Yes,6.9,6.5,13.4
4,Rocky Road,Chocolate,Yes,8.2,7.0,15.2
5,Pistachio,Vanilla,No,2.3,3.4,5.7
6,Cake Batter,Vanilla,Yes,6.5,6.0,12.5
7,Neapolitan,Vanilla,No,3.8,5.0,8.8
8,Chocolte Fudge Brownie,Chocolate,Yes,8.2,7.1,15.3

## Finding the specific data using its Location

In [6]:
df.loc[1]

Flavor            Chocolate
Base Flavor       Chocolate
Liked                   Yes
Flavor Rating           8.8
Texture Rating          7.6
Total Rating           16.6
Name: 1, dtype: object

## Setting the Index as Flavor

In [10]:
df2 = df.set_index('Flavor')
df2

,Base Flavor,Liked,Flavor Rating,Texture Rating,Total Rating
Flavor,,,,,
Mint Chocolate Chip,Vanilla,Yes,10.0,8.0,18.0
Chocolate,Chocolate,Yes,8.8,7.6,16.6
Vanilla,Vanilla,No,4.7,5.0,9.7
Cookie Dough,Vanilla,Yes,6.9,6.5,13.4
Rocky Road,Chocolate,Yes,8.2,7.0,15.2
Pistachio,Vanilla,No,2.3,3.4,5.7
Cake Batter,Vanilla,Yes,6.5,6.0,12.5
Neapolitan,Vanilla,No,3.8,5.0,8.8
Chocolte Fudge Brownie,Chocolate,Yes,8.2,7.1,15.3

## Finding the row where Flavor is Vanilla

In [15]:
d = df.loc[df['Flavor'] == 'Vanilla']
d

    Flavor Base Flavor Liked  Flavor Rating  Texture Rating  Total Rating
2  Vanilla     Vanilla    No            4.7             5.0           9.7

## Finding Total by Flavor

In [37]:
df = df.groupby('Flavor').sum()
df

,Base Flavor,Liked,Flavor Rating,Texture Rating,Total Rating
Flavor,,,,,
Cake Batter,Vanilla,Yes,6.5,6.0,12.5
Chocolate,Chocolate,Yes,8.8,7.6,16.6
Chocolte Fudge Brownie,Chocolate,Yes,8.2,7.1,15.3
Cookie Dough,Vanilla,Yes,6.9,6.5,13.4
Mint Chocolate Chip,Vanilla,Yes,10.0,8.0,18.0
Neapolitan,Vanilla,No,3.8,5.0,8.8
Pistachio,Vanilla,No,2.3,3.4,5.7
Rocky Road,Chocolate,Yes,8.2,7.0,15.2
Vanilla,Vanilla,No,4.7,5.0,9.7

## Aggregating on Specific Columns

In [38]:
df.groupby(['Base Flavor','Liked']).agg({'Flavor Rating':['mean','sum','count'], 'Total Rating' : ['mean','sum','count'] })

                  Flavor Rating             Total Rating
                           mean   sum count         mean   sum count
Base Flavor Liked
Chocolate   Yes             8.4  25.2     3    15.700000  47.1     3
Vanilla     No              3.6  10.8     3     8.066667  24.2     3
            Yes             7.8  23.4     3    14.633333  43.9     3