In [1]:
!pip3 install matplotlib
!pip3 install seaborn
!pip3 install pandas
!pip3 install numpy
!pip3 install --upgrade pip

Requirement already satisfied: matplotlib in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (3.9.1)
Requirement already satisfied: contourpy>=1.0.1 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from matplotlib) (1.2.1)
Requirement already satisfied: cycler>=0.10 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from matplotlib) (4.53.1)
Requirement already satisfied: kiwisolver>=1.3.1 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from matplotlib) (1.4.5)
Requirement already satisfied: numpy>=1.23 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from matplotlib) (2.0.0)
Requirement already satisfied: packaging>=20.0 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from matplotlib) (24.1)
Requirement already satisfied: pillow>=8 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from matplotlib) (10.4.0)
Requirement already satisfied: pyparsing>=2.3.1 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from matplotlib) (3.1.2)
Requirement already satisfied: python-dateutil>=2.7 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from matplotlib) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from python-dateutil>=2.7->matplotlib) (1.16.0)
Requirement already satisfied: seaborn in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (0.13.2)
Requirement already satisfied: numpy!=1.24.0,>=1.20 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from seaborn) (2.0.0)
Requirement already satisfied: pandas>=1.2 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from seaborn) (2.2.2)
Requirement already satisfied: matplotlib!=3.6.1,>=3.4 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from seaborn) (3.9.1)
Requirement already satisfied: contourpy>=1.0.1 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (1.2.1)
Requirement already satisfied: cycler>=0.10 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (4.53.1)
Requirement already satisfied: kiwisolver>=1.3.1 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (1.4.5)
Requirement already satisfied: packaging>=20.0 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (24.1)
Requirement already satisfied: pillow>=8 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (10.4.0)
Requirement already satisfied: pyparsing>=2.3.1 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (3.1.2)
Requirement already satisfied: python-dateutil>=2.7 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from pandas>=1.2->seaborn) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from pandas>=1.2->seaborn) (2024.1)
Requirement already satisfied: six>=1.5 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from python-dateutil>=2.7->matplotlib!=3.6.1,>=3.4->seaborn) (1.16.0)
Requirement already satisfied: pandas in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from pandas) (2.0.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from pandas) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from pandas) (2024.1)
Requirement already satisfied: six>=1.5 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Requirement already satisfied: numpy in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (2.0.0)
Requirement already satisfied: pip in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (24.1.2)

In [2]:
import numpy as np
import pandas as pd
import seaborn as sns

In [22]:
df = pd.read_csv(r"/Users/jiyadariyani/Documents/Projects/Python Projects/Customer_Call_List.csv")
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Not_Useful_Column,Unnamed: 8,Unnamed: 9
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,No,True,NaN,NaN
1,1002,Abed,Nadir,123/643/9775,93 West Main Street,No,Yes,False,NaN,NaN
2,1003,Walter,/White,7066950392,298 Drugs Driveway,N,NaN,True,NaN,NaN
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y,True,NaN,NaN
4,1005,Jon,Snow,876|678|3469,123 Dragons Road,Y,No,True,NaN,NaN
5,1006,Ron,Swanson,304-762-2467,768 City Parkway,Yes,Yes,True,NaN,NaN
6,1007,Jeff,Winger,NaN,1209 South Street,No,No,False,NaN,NaN
7,1008,Sherlock,Holmes,876|678|3469,98 Clue Drive,N,No,False,NaN,NaN
8,1009,Gandalf,NaN,N/a,123 Middle Earth,Yes,NaN,False,NaN,NaN
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Yes,No,True,NaN,NaN
10,1011,Samwise,Gamgee,NaN,"612 Shire Lane, Shire",Yes,No,True,NaN,NaN
11,1012,Harry,...Potter,7066950392,2394 Hogwarts Avenue,Y,NaN,True,NaN,NaN
12,1013,Don,Draper,123-543-2345,2039 Main Street,Yes,N,False,NaN,NaN
13,1014,Leslie,Knope,876|678|3469,343 City Parkway,Yes,No,False,NaN,NaN
14,1015,Toby,Flenderson_,304-762-2467,214 HR Avenue,N,No,False,NaN,NaN
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,No,N,False,NaN,NaN
16,1017,Michael,Scott,123/643/9775,"121 Paper Avenue, Pennsylvania",Yes,No,False,NaN,NaN
17,1018,Clark,Kent,7066950392,3498 Super Lane,Y,NaN,True,NaN,NaN
18,1019,Creed,Braton,N/a,N/a,N/a,Yes,True,NaN,NaN
19,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N,True,NaN,NaN
20,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N,True,NaN,NaN

In [29]:
df = df.drop(columns = "Unnamed: 9")
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,No
1,1002,Abed,Nadir,123/643/9775,93 West Main Street,No,Yes
2,1003,Walter,/White,7066950392,298 Drugs Driveway,N,NaN
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y
4,1005,Jon,Snow,876|678|3469,123 Dragons Road,Y,No
5,1006,Ron,Swanson,304-762-2467,768 City Parkway,Yes,Yes
6,1007,Jeff,Winger,NaN,1209 South Street,No,No
7,1008,Sherlock,Holmes,876|678|3469,98 Clue Drive,N,No
8,1009,Gandalf,NaN,N/a,123 Middle Earth,Yes,NaN
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Yes,No
10,1011,Samwise,Gamgee,NaN,"612 Shire Lane, Shire",Yes,No
11,1012,Harry,...Potter,7066950392,2394 Hogwarts Avenue,Y,NaN
12,1013,Don,Draper,123-543-2345,2039 Main Street,Yes,N
13,1014,Leslie,Knope,876|678|3469,343 City Parkway,Yes,No
14,1015,Toby,Flenderson_,304-762-2467,214 HR Avenue,N,No
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,No,N
16,1017,Michael,Scott,123/643/9775,"121 Paper Avenue, Pennsylvania",Yes,No
17,1018,Clark,Kent,7066950392,3498 Super Lane,Y,NaN
18,1019,Creed,Braton,N/a,N/a,N/a,Yes
19,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N
20,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N

In [30]:
# Removing duplicates
df = df.drop_duplicates()
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,No
1,1002,Abed,Nadir,123/643/9775,93 West Main Street,No,Yes
2,1003,Walter,/White,7066950392,298 Drugs Driveway,N,NaN
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y
4,1005,Jon,Snow,876|678|3469,123 Dragons Road,Y,No
5,1006,Ron,Swanson,304-762-2467,768 City Parkway,Yes,Yes
6,1007,Jeff,Winger,NaN,1209 South Street,No,No
7,1008,Sherlock,Holmes,876|678|3469,98 Clue Drive,N,No
8,1009,Gandalf,NaN,N/a,123 Middle Earth,Yes,NaN
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Yes,No
10,1011,Samwise,Gamgee,NaN,"612 Shire Lane, Shire",Yes,No
11,1012,Harry,...Potter,7066950392,2394 Hogwarts Avenue,Y,NaN
12,1013,Don,Draper,123-543-2345,2039 Main Street,Yes,N
13,1014,Leslie,Knope,876|678|3469,343 City Parkway,Yes,No
14,1015,Toby,Flenderson_,304-762-2467,214 HR Avenue,N,No
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,No,N
16,1017,Michael,Scott,123/643/9775,"121 Paper Avenue, Pennsylvania",Yes,No
17,1018,Clark,Kent,7066950392,3498 Super Lane,Y,NaN
18,1019,Creed,Braton,N/a,N/a,N/a,Yes
19,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N

In [33]:
#Standardizing Data
df = df.copy()
df['Last_Name'] = df['Last_Name'].str.strip("./_")
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,No
1,1002,Abed,Nadir,123/643/9775,93 West Main Street,No,Yes
2,1003,Walter,White,7066950392,298 Drugs Driveway,N,NaN
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y
4,1005,Jon,Snow,876|678|3469,123 Dragons Road,Y,No
5,1006,Ron,Swanson,304-762-2467,768 City Parkway,Yes,Yes
6,1007,Jeff,Winger,NaN,1209 South Street,No,No
7,1008,Sherlock,Holmes,876|678|3469,98 Clue Drive,N,No
8,1009,Gandalf,NaN,N/a,123 Middle Earth,Yes,NaN
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Yes,No
10,1011,Samwise,Gamgee,NaN,"612 Shire Lane, Shire",Yes,No
11,1012,Harry,Potter,7066950392,2394 Hogwarts Avenue,Y,NaN
12,1013,Don,Draper,123-543-2345,2039 Main Street,Yes,N
13,1014,Leslie,Knope,876|678|3469,343 City Parkway,Yes,No
14,1015,Toby,Flenderson,304-762-2467,214 HR Avenue,N,No
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,No,N
16,1017,Michael,Scott,123/643/9775,"121 Paper Avenue, Pennsylvania",Yes,No
17,1018,Clark,Kent,7066950392,3498 Super Lane,Y,NaN
18,1019,Creed,Braton,N/a,N/a,N/a,Yes
19,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N

In [35]:
#df["Phone_Number"] = df["Phone_Number"].apply(lambda x : str(x))
#str(df["Phone_Number"])
#Standardizing the Columns
df["Phone_Number"] = df["Phone_Number"].str.replace('[^a-zA-Z0-9]','',regex=True)
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact
0,1001,Frodo,Baggins,1235455421,"123 Shire Lane, Shire",Yes,No
1,1002,Abed,Nadir,1236439775,93 West Main Street,No,Yes
2,1003,Walter,White,7066950392,298 Drugs Driveway,N,NaN
3,1004,Dwight,Schrute,1235432345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y
4,1005,Jon,Snow,8766783469,123 Dragons Road,Y,No
5,1006,Ron,Swanson,3047622467,768 City Parkway,Yes,Yes
6,1007,Jeff,Winger,NaN,1209 South Street,No,No
7,1008,Sherlock,Holmes,8766783469,98 Clue Drive,N,No
8,1009,Gandalf,NaN,Na,123 Middle Earth,Yes,NaN
9,1010,Peter,Parker,1235455421,"25th Main Street, New York",Yes,No
10,1011,Samwise,Gamgee,NaN,"612 Shire Lane, Shire",Yes,No
11,1012,Harry,Potter,7066950392,2394 Hogwarts Avenue,Y,NaN
12,1013,Don,Draper,1235432345,2039 Main Street,Yes,N
13,1014,Leslie,Knope,8766783469,343 City Parkway,Yes,No
14,1015,Toby,Flenderson,3047622467,214 HR Avenue,N,No
15,1016,Ron,Weasley,1235455421,2395 Hogwarts Avenue,No,N
16,1017,Michael,Scott,1236439775,"121 Paper Avenue, Pennsylvania",Yes,No
17,1018,Clark,Kent,7066950392,3498 Super Lane,Y,NaN
18,1019,Creed,Braton,Na,N/a,N/a,Yes
19,1020,Anakin,Skywalker,8766783469,"910 Tatooine Road, Tatooine",Yes,N

In [39]:
#df["Phone_Number"] = df["Phone_Number"].str.replace('nan','', regex=False)
#df["Phone_Number"] = df["Phone_Number"].str.replace('Na','', regex=False)
str(df["Phone_Number"])

'0     1235455421\n1     1236439775\n2     7066950392\n3     1235432345\n4     8766783469\n5     3047622467\n6            NaN\n7     8766783469\n8             Na\n9     1235455421\n10           NaN\n11    7066950392\n12    1235432345\n13    8766783469\n14    3047622467\n15    1235455421\n16    1236439775\n17    7066950392\n18            Na\n19    8766783469\nName: Phone_Number, dtype: object'

In [41]:
df["Phone_Number"] = df["Phone_Number"].apply(lambda x : str(x))
df["Phone_Number"] = df["Phone_Number"].apply(lambda x: x[0:3] + '-' + x[3:6] + '-' + x[6:10])
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,No
1,1002,Abed,Nadir,123-643-9775,93 West Main Street,No,Yes
2,1003,Walter,White,706-695-0392,298 Drugs Driveway,N,NaN
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y
4,1005,Jon,Snow,876-678-3469,123 Dragons Road,Y,No
5,1006,Ron,Swanson,304-762-2467,768 City Parkway,Yes,Yes
6,1007,Jeff,Winger,nan--,1209 South Street,No,No
7,1008,Sherlock,Holmes,876-678-3469,98 Clue Drive,N,No
8,1009,Gandalf,NaN,Na--,123 Middle Earth,Yes,NaN
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Yes,No
10,1011,Samwise,Gamgee,nan--,"612 Shire Lane, Shire",Yes,No
11,1012,Harry,Potter,706-695-0392,2394 Hogwarts Avenue,Y,NaN
12,1013,Don,Draper,123-543-2345,2039 Main Street,Yes,N
13,1014,Leslie,Knope,876-678-3469,343 City Parkway,Yes,No
14,1015,Toby,Flenderson,304-762-2467,214 HR Avenue,N,No
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,No,N
16,1017,Michael,Scott,123-643-9775,"121 Paper Avenue, Pennsylvania",Yes,No
17,1018,Clark,Kent,706-695-0392,3498 Super Lane,Y,NaN
18,1019,Creed,Braton,Na--,N/a,N/a,Yes
19,1020,Anakin,Skywalker,876-678-3469,"910 Tatooine Road, Tatooine",Yes,N

In [42]:
#Removing Unwanted rows
df["Phone_Number"] = df["Phone_Number"].str.replace('nan--','', regex=False)
df["Phone_Number"] = df["Phone_Number"].str.replace('Na--','', regex=False)
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,No
1,1002,Abed,Nadir,123-643-9775,93 West Main Street,No,Yes
2,1003,Walter,White,706-695-0392,298 Drugs Driveway,N,NaN
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y
4,1005,Jon,Snow,876-678-3469,123 Dragons Road,Y,No
5,1006,Ron,Swanson,304-762-2467,768 City Parkway,Yes,Yes
6,1007,Jeff,Winger,,1209 South Street,No,No
7,1008,Sherlock,Holmes,876-678-3469,98 Clue Drive,N,No
8,1009,Gandalf,NaN,,123 Middle Earth,Yes,NaN
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Yes,No
10,1011,Samwise,Gamgee,,"612 Shire Lane, Shire",Yes,No
11,1012,Harry,Potter,706-695-0392,2394 Hogwarts Avenue,Y,NaN
12,1013,Don,Draper,123-543-2345,2039 Main Street,Yes,N
13,1014,Leslie,Knope,876-678-3469,343 City Parkway,Yes,No
14,1015,Toby,Flenderson,304-762-2467,214 HR Avenue,N,No
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,No,N
16,1017,Michael,Scott,123-643-9775,"121 Paper Avenue, Pennsylvania",Yes,No
17,1018,Clark,Kent,706-695-0392,3498 Super Lane,Y,NaN
18,1019,Creed,Braton,,N/a,N/a,Yes
19,1020,Anakin,Skywalker,876-678-3469,"910 Tatooine Road, Tatooine",Yes,N

In [49]:
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",N,No
1,1002,Abed,Nadir,123-643-9775,93 West Main Street,Yes,Yes
2,1003,Walter,White,706-695-0392,298 Drugs Driveway,NaN,NaN
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Y,Y
4,1005,Jon,Snow,876-678-3469,123 Dragons Road,N,No
5,1006,Ron,Swanson,304-762-2467,768 City Parkway,Yes,Yes
6,1007,Jeff,Winger,,1209 South Street,N,No
7,1008,Sherlock,Holmes,876-678-3469,98 Clue Drive,N,No
8,1009,Gandalf,NaN,,123 Middle Earth,NaN,NaN
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",N,No
10,1011,Samwise,Gamgee,,"612 Shire Lane, Shire",N,No
11,1012,Harry,Potter,706-695-0392,2394 Hogwarts Avenue,NaN,NaN
12,1013,Don,Draper,123-543-2345,2039 Main Street,N,N
13,1014,Leslie,Knope,876-678-3469,343 City Parkway,N,No
14,1015,Toby,Flenderson,304-762-2467,214 HR Avenue,N,No
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,N,N
16,1017,Michael,Scott,123-643-9775,"121 Paper Avenue, Pennsylvania",N,No
17,1018,Clark,Kent,706-695-0392,3498 Super Lane,NaN,NaN
18,1019,Creed,Braton,,N/a,Yes,Yes
19,1020,Anakin,Skywalker,876-678-3469,"910 Tatooine Road, Tatooine",N,N

In [58]:
df["Do_Not_Contact"] = df["Do_Not_Contact"].replace('Yes', 'Y')

In [59]:
df["Do_Not_Contact"]

0      No
1       Y
2     NaN
3       Y
4      No
5       Y
6      No
7      No
8     NaN
9      No
10     No
11    NaN
12      N
13     No
14     No
15      N
16     No
17    NaN
18      Y
19      N
Name: Do_Not_Contact, dtype: object

In [61]:
df["Do_Not_Contact"] = df["Do_Not_Contact"].replace('No', 'N')

In [62]:
df["Do_Not_Contact"]

0       N
1       Y
2     NaN
3       Y
4       N
5       Y
6       N
7       N
8     NaN
9       N
10      N
11    NaN
12      N
13      N
14      N
15      N
16      N
17    NaN
18      Y
19      N
Name: Do_Not_Contact, dtype: object

In [63]:
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",N,N
1,1002,Abed,Nadir,123-643-9775,93 West Main Street,Yes,Y
2,1003,Walter,White,706-695-0392,298 Drugs Driveway,NaN,NaN
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Y,Y
4,1005,Jon,Snow,876-678-3469,123 Dragons Road,N,N
5,1006,Ron,Swanson,304-762-2467,768 City Parkway,Yes,Y
6,1007,Jeff,Winger,,1209 South Street,N,N
7,1008,Sherlock,Holmes,876-678-3469,98 Clue Drive,N,N
8,1009,Gandalf,NaN,,123 Middle Earth,NaN,NaN
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",N,N
10,1011,Samwise,Gamgee,,"612 Shire Lane, Shire",N,N
11,1012,Harry,Potter,706-695-0392,2394 Hogwarts Avenue,NaN,NaN
12,1013,Don,Draper,123-543-2345,2039 Main Street,N,N
13,1014,Leslie,Knope,876-678-3469,343 City Parkway,N,N
14,1015,Toby,Flenderson,304-762-2467,214 HR Avenue,N,N
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,N,N
16,1017,Michael,Scott,123-643-9775,"121 Paper Avenue, Pennsylvania",N,N
17,1018,Clark,Kent,706-695-0392,3498 Super Lane,NaN,NaN
18,1019,Creed,Braton,,N/a,Yes,Y
19,1020,Anakin,Skywalker,876-678-3469,"910 Tatooine Road, Tatooine",N,N

In [64]:
df["Paying Customer"] = df["Paying Customer"].replace('Yes', 'Y')

In [65]:
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",N,N
1,1002,Abed,Nadir,123-643-9775,93 West Main Street,Y,Y
2,1003,Walter,White,706-695-0392,298 Drugs Driveway,NaN,NaN
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Y,Y
4,1005,Jon,Snow,876-678-3469,123 Dragons Road,N,N
5,1006,Ron,Swanson,304-762-2467,768 City Parkway,Y,Y
6,1007,Jeff,Winger,,1209 South Street,N,N
7,1008,Sherlock,Holmes,876-678-3469,98 Clue Drive,N,N
8,1009,Gandalf,NaN,,123 Middle Earth,NaN,NaN
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",N,N
10,1011,Samwise,Gamgee,,"612 Shire Lane, Shire",N,N
11,1012,Harry,Potter,706-695-0392,2394 Hogwarts Avenue,NaN,NaN
12,1013,Don,Draper,123-543-2345,2039 Main Street,N,N
13,1014,Leslie,Knope,876-678-3469,343 City Parkway,N,N
14,1015,Toby,Flenderson,304-762-2467,214 HR Avenue,N,N
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,N,N
16,1017,Michael,Scott,123-643-9775,"121 Paper Avenue, Pennsylvania",N,N
17,1018,Clark,Kent,706-695-0392,3498 Super Lane,NaN,NaN
18,1019,Creed,Braton,,N/a,Y,Y
19,1020,Anakin,Skywalker,876-678-3469,"910 Tatooine Road, Tatooine",N,N

In [75]:
df = df.fillna('')

In [76]:
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",N,N
1,1002,Abed,Nadir,123-643-9775,93 West Main Street,Y,Y
2,1003,Walter,White,706-695-0392,298 Drugs Driveway,,
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Y,Y
4,1005,Jon,Snow,876-678-3469,123 Dragons Road,N,N
5,1006,Ron,Swanson,304-762-2467,768 City Parkway,Y,Y
6,1007,Jeff,Winger,,1209 South Street,N,N
7,1008,Sherlock,Holmes,876-678-3469,98 Clue Drive,N,N
8,1009,Gandalf,,,123 Middle Earth,,
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",N,N
10,1011,Samwise,Gamgee,,"612 Shire Lane, Shire",N,N
11,1012,Harry,Potter,706-695-0392,2394 Hogwarts Avenue,,
12,1013,Don,Draper,123-543-2345,2039 Main Street,N,N
13,1014,Leslie,Knope,876-678-3469,343 City Parkway,N,N
14,1015,Toby,Flenderson,304-762-2467,214 HR Avenue,N,N
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,N,N
16,1017,Michael,Scott,123-643-9775,"121 Paper Avenue, Pennsylvania",N,N
17,1018,Clark,Kent,706-695-0392,3498 Super Lane,,
18,1019,Creed,Braton,,N/a,Y,Y
19,1020,Anakin,Skywalker,876-678-3469,"910 Tatooine Road, Tatooine",N,N

In [87]:
for x in df.index:
        if df.loc[x,"Do_Not_Contact"] == 'Y' :
            df.drop(x, inplace=True)
    
        
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",N,N
2,1003,Walter,White,706-695-0392,298 Drugs Driveway,,
4,1005,Jon,Snow,876-678-3469,123 Dragons Road,N,N
6,1007,Jeff,Winger,,1209 South Street,N,N
7,1008,Sherlock,Holmes,876-678-3469,98 Clue Drive,N,N
8,1009,Gandalf,,,123 Middle Earth,,
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",N,N
10,1011,Samwise,Gamgee,,"612 Shire Lane, Shire",N,N
11,1012,Harry,Potter,706-695-0392,2394 Hogwarts Avenue,,
12,1013,Don,Draper,123-543-2345,2039 Main Street,N,N
13,1014,Leslie,Knope,876-678-3469,343 City Parkway,N,N
14,1015,Toby,Flenderson,304-762-2467,214 HR Avenue,N,N
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,N,N
16,1017,Michael,Scott,123-643-9775,"121 Paper Avenue, Pennsylvania",N,N
17,1018,Clark,Kent,706-695-0392,3498 Super Lane,,
19,1020,Anakin,Skywalker,876-678-3469,"910 Tatooine Road, Tatooine",N,N

In [88]:
for x in df.index:
        if df.loc[x,"Phone_Number"] == '' :
            df.drop(x, inplace=True)
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",N,N
2,1003,Walter,White,706-695-0392,298 Drugs Driveway,,
4,1005,Jon,Snow,876-678-3469,123 Dragons Road,N,N
7,1008,Sherlock,Holmes,876-678-3469,98 Clue Drive,N,N
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",N,N
11,1012,Harry,Potter,706-695-0392,2394 Hogwarts Avenue,,
12,1013,Don,Draper,123-543-2345,2039 Main Street,N,N
13,1014,Leslie,Knope,876-678-3469,343 City Parkway,N,N
14,1015,Toby,Flenderson,304-762-2467,214 HR Avenue,N,N
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,N,N
16,1017,Michael,Scott,123-643-9775,"121 Paper Avenue, Pennsylvania",N,N
17,1018,Clark,Kent,706-695-0392,3498 Super Lane,,
19,1020,Anakin,Skywalker,876-678-3469,"910 Tatooine Road, Tatooine",N,N